site_name: VANET Workshop
theme:
  name: material
  logo: assets/logo.svg
  palette:
    scheme: slate
    primary: black
  custom_dir: overrides
  features:
    - navigation.footer

extra:
  generator: false
