site_name: VANET Workshop
theme:
  name: material
  logo: assets/logo.svg
  palette:
    scheme: slate
    primary: black
  custom_dir: overrides
  features:
    - navigation.footer
    - content.code.copy
  font:
    # text: Inconsolata
    # text: Single Day
    text: Tenor Sans

extra:
  generator: false


